name: HypertechLighting
favicon: null
layout_spectrum: 0.3062774573918432
typography_spectrum: 0.7112223247531801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070b0e'
    - '#979aa9'
    - '#adcce9'
    - '#3f608d'
  brandStrength: 0.06516470154747367
  lightness: 0.77615826879628
  saturation: 0.6722418514546007
  rhythmicContrast: 0.08004789729602635
purpose: []
